### ISSUE TITLE
Could you please tell me how to draw classification results as the color adopted in mostly used methods? Just as follows.

### ISSUE THREAD

**Issue by Anleeno** [qichaoliu/CNN_Enhanced_GCN#8]
![indian_0 99100482022-10-31-18-31-37](https://user-images.githubusercontent.com/41414217/206078815-8eabf9e3-a48e-4202-a1c4-bbe89b7e94bf.png)
![predictions_indian](https://user-images.githubusercontent.com/41414217/206078827-da15e179-30a3-4c0c-8f17-8874ea0b21f4.jpg)

or adjust it as shown in your paper.

**Comment by qichaoliu** [comment]
You can refer to the Python Library named "spectral". http://www.spectralpython.net/
